sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t minthoang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true minthoang/docker-react npm run test
